stages:
- gitlab
- test
- deploy

include:
- template: Dependency-Scanning.gitlab-ci.yml
- template: Security/SAST.gitlab-ci.yml

sast:
  stage: gitlab

dependency_scanning:
  stage: gitlab
  before_script:
  - apt-get update && apt-get install redis-server libmariadbclient-dev -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox

test-3.6-core:
  image: python:3.6-buster
  script:  
  - tox -e py36-core
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

test-3.7-core:
  image: python:3.7-buster
  script:  
  - tox -e py37-core
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

test-3.8-core:
  image: python:3.8-buster
  script:  
  - tox -e py38-core
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

test-3.9-core:
  image: python:3.9-buster
  script:  
  - tox -e py39-core
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

test-3.6-all:
  image: python:3.6-buster
  script:  
  - tox -e py36-all
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

test-3.7-all:
  image: python:3.7-buster
  script:  
  - tox -e py37-all
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

test-3.8-all:
  image: python:3.8-buster
  script:  
  - tox -e py38-all
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

test-3.9-all:
  image: python:3.9-buster
  script:  
  - tox -e py39-all
  before_script:
  - apt-get update && apt-get install redis-server -y
  - redis-server --daemonize yes
  - redis-cli ping
  - python -V
  - pip install wheel tox
  artifacts:
    when: always
    reports:
      cobertura: coverage.xml

deploy_production:
  stage: deploy
  image: python:3.9-buster

  before_script:
    - pip install twine wheel

  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*

  rules:
    - if: $CI_COMMIT_TAG